/*
 * File: Makefile
 * Date: 01.12.2015
 * Author: Ján Gula,xgulaj00
 * Project: IZP-DU3
 * Description: Makefile.
*/

CFLAGS=-std=c99 -Wall -Wextra -pedantic -g -DNDEBUG
LDFLAGS=-lm
proj3: proj3.c
clean:
	-rm proj3 proj3.c
